### ISSUE TITLE
Cannot update to latest version

### ISSUE THREAD

**Issue by kaiiyer** [kaiiyer/webtech#18]
$ webtech --update 
command is not working on debian9

**Comment by svensevenslow** [comment]
Hey! I'd like to work on this. Also I'll be using a VM to run debian9 since I don't use this OS.

**Comment by svensevenslow** [comment]
Hi! I first setup up webtech on Fedora 30 and tried running webtech -u https://example.com/. It worked fine I got this as output:
Target URL: https://example.com/
Detected technologies:
	- Amazon ECS 
Now I have set up a VM which runs Debian 9 OS. I setup up the webtech on this os just as I did for Fedora. However the output I'm receiving by running webtech -u https://example.com or any other webtech command like webtech -h is:
bash: webtech: command not found
Just wanted to know if I'm this is how it's supposed to be or just the webtech --update command doesn't work?

**Comment by ashwinijha6** [comment]
I want to work on this

**Comment by ashwinijha6** [comment]
![debian](https://user-images.githubusercontent.com/45794450/75117767-68b70a80-569a-11ea-9b58-fc80aa64f899.JPG)

**Comment by ashwinijha6** [comment]
command is working on debian 10

**Comment by ashwinijha6** [comment]
Should I try it on debian 9 as well
