### ISSUE TITLE
Add script to scrape information from web pages

### ISSUE THREAD

**Issue by kaiiyer** [kaiiyer/webtech#19]
Use beautiful soup (bs4) to make a script so that the user can scrape information from web pages.

**Comment by tinaoberoi** [comment]
I would like to work on this.

**Comment by kaiiyer** [comment]
Okay !! I've assigned the issue to you @tinaoberoi

**Comment by nishit130** [comment]
Hello, @tinaoberoi are you still working on this issue?

**Comment by tinaoberoi** [comment]
Yes @nis130

**Comment by sanjanaagrawal** [comment]
Please assign this issue to me.

**Comment by kaiiyer** [comment]
Someone is working on it. Please wait for a few days @sanjanaagrawal

**Comment by aayush1205** [comment]
Could you please elaborate on what kind of information scraping are we looking at?

**Comment by kaiiyer** [comment]
I guess this might help
https://medium.com/@heavenraiza/web-scraping-with-python-170145fd90d3

**Comment by aayush1205** [comment]
Is this still active?

**Comment by utkarsh-raj** [comment]
I am assigning @aayush1205 . Please understand that in fairness of the ongoing contest, we have to limit the time assigned to medium issues to three days.

**Comment by puneethkanna** [comment]
Could you please elaborate on what kind of data to scrape,
+ Headings
+ Images
etc..

**Comment by kaiiyer** [comment]
Headings will do !

**Comment by aayush1205** [comment]
@kaiiyer I'm still working on the issue, sir.

**Comment by aayush1205** [comment]
Also, @kaiiyer the script is really open ended in a sense that the user might give any website to scrape right? For instance, scraping YouTube is very different than let's say scraping Wikipedia. Henceforth, I'm leaving the script open for feature addition and right now am tackling the scraping of general info like links etc for any given website. Sounds allright?

**Comment by kaiiyer** [comment]
Yeah cool

**Comment by aayush1205** [comment]
If I have cloned your repository, what command do I run (in terms of python somefile.py -u google.com) to simulate the symlink command of webtech -u google.com @kaiiyer

**Comment by kaiiyer** [comment]
Why do you wanna simulate it in first place ?
webtech as a whole is a library you can't use a single python file to do the same job

**Comment by kaiiyer** [comment]
@utkarsh-raj will help you out with your queries @aayush1205

**Comment by aayush1205** [comment]
@kaiiyer agreeably. But then, if I make changes to some files, for reference take a look at #46 , how do I test them. @utkarsh-raj

**Comment by aayush1205** [comment]
@kaiiyer, now can this be closed?

**Comment by kaiiyer** [comment]
Yeah

**Comment by aayush1205** [comment]
@kaiiyer, Thank you so much. Also, for some reason, my score is not updating.

**Comment by kaiiyer** [comment]
@utkarsh-raj can help you with that !

**Comment by aayush1205** [comment]
@kaiiyer, @utkarsh-raj The score for this issue was not added to my profile. Please see to it.

**Comment by koderjoker** [comment]
@aayush1205 I've updated your score

**Comment by aayush1205** [comment]
@koderjoker , Thanks a lot. I also wanted to ask if more issues will be added for us to solve.

**Comment by koderjoker** [comment]
You'll have to refer to @kaiiyer regarding the roadmap of the project.
