### ISSUE TITLE
Add a web inteface for the CLI tool

### ISSUE THREAD

**Issue by kaiiyer** [kaiiyer/webtech#21]
create a web app for using the tool from a browser.

**Comment by ghost** [comment]
Can we use Flask to make into web app ??

**Comment by kaiiyer** [comment]
Yeah that's a good idea !!

**Comment by ghost** [comment]
Ok , can I take it up ??

**Comment by Ramas1998** [comment]
I would like to work on this

**Comment by utkarsh-raj** [comment]
Hey @sagnik-chatterjee are you still working on the issue? Can you please update the status of your progress?

**Comment by sagnik-chatterjee** [comment]
Yeah , I am working on it ,albeit a little slow as my University mid sem exams are also going on ..so I may able slow to send a pull request.

**Comment by ghost** [comment]
Hi @utkarsh-raj , you are free to take up this issue ...

**Comment by utkarsh-raj** [comment]
Thanks for the information @sagnik-chatterjee . I am assigning @Ramas1998 to take this up!

**Comment by utkarsh-raj** [comment]
Can you update the progress @Ramas1998 ?

**Comment by Ramas1998** [comment]
Hey Kaiiyer,
I am still working on this issue can u give time till sunday as i had a
conference presentation yesterday.

**Comment by Ramas1998** [comment]
I am using flask for the app also  would get details about the technolgy
for the given website from cli.

**Comment by kaiiyer** [comment]
What's the process be like @Ramas1998
