### ISSUE TITLE
Add continuous integration workflow for deploying code

### ISSUE THREAD

**Issue by kaiiyer** [kaiiyer/webtech#22]
Set up Github Actions.
Choose a workflow to build, test, and deploy the code. Make code reviews, branch management, and issue triaging work the way you want.

**Comment by tinaoberoi** [comment]
I would like to work on this.

**Comment by kaiiyer** [comment]
I've set up CircleCI. So you can work with Travis or Git Actions !

**Comment by Ramas1998** [comment]
I too want to work on thia issue

**Comment by kaiiyer** [comment]
Can you wait for a few days as someone is already working on this !!

**Comment by kaiiyer** [comment]
@tinaoberoi Any updates ?

**Comment by poojasrinivass** [comment]
I would like to work on this issue

**Comment by utkarsh-raj** [comment]
I am assigning @Ramas1998 to take this up. If you they would like to work on the other issues assigned to them on a prior basis, please let us know so that @poojasrinivass can be assigned. Please understand that in fairness of the ongoing contest, we have to limit the time assigned to easy issues to two days.

**Comment by Ramas1998** [comment]
Hey,
As i have already issue 21 to be continued u can assign it to someone else.

**Comment by kaiiyer** [comment]
Any Updates ?

**Comment by keshakaneria** [comment]
Yes i would like to take up this issue @kaiiyer

**Comment by Akansha2202** [comment]
I would like to contribute

**Comment by kaiiyer** [comment]
@utkarsh-raj Look into it !

**Comment by aliana17** [comment]
I would also like to contribute @kaiiyer
