### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by kaiiyer** [kaiiyer/webtech#23]
**Documentation for users**
A documentation of the tool for new users to handle it efficiently.
Create a docs folder and create doc for github hosting

**Comment by Tawishi** [comment]
I would like to work on this issue.

**Comment by kaiiyer** [comment]
Okay I've assigned you the issue !!

**Comment by Tawishi** [comment]
I am unable to use the tool after installing.
![Screenshot from 2020-02-22 22-20-48](https://user-images.githubusercontent.com/55306738/75096086-e6f3ae00-55c1-11ea-8292-f3e406161381.png)

**Comment by kaiiyer** [comment]
Add the directory having the binary to the PATH variable

**Comment by Tawishi** [comment]
Is this correct ?
![Screenshot from 2020-02-24 14-57-31](https://user-images.githubusercontent.com/55306738/75141040-229f8c80-5716-11ea-8975-3feacbcc5c9c.png)

**Comment by Tawishi** [comment]
Its working alright :+1:
Please specify the pointers needed in the documentation.

**Comment by kaiiyer** [comment]
> Its working alright +1
> Please specify the pointers needed in the documentation.

for eg.
Info about the Burpsuite for those who don't know burp
then details on the options available for the tool(a simple description is already provided in tool itself)

**Comment by keshakaneria** [comment]
Can you assign it to 2 people even i want to help @Tawishi to create documentation ready?

**Comment by kaiiyer** [comment]
Yeah that's totally fine !!
Please discuss among yourself about the distribution of work. If any issue pops up please do comment here !!!

**Comment by ghost** [comment]
I would love to document this project.

**Comment by kaiiyer** [comment]
> I would love to document this project.

Yeah go on !!!

**Comment by Tawishi** [comment]
These errors are popping up.Please help.
![Screenshot from 2020-03-03 10-57-11](https://user-images.githubusercontent.com/55306738/75745611-dcfa4980-5d3d-11ea-9dbe-4d958e536be0.png)

**Comment by kaiiyer** [comment]
Remove webtech from your system and reinstall it again to see whether the error persists !

**Comment by Tawishi** [comment]
> Remove webtech from your system and reinstall it again to see whether the error persists !

This is what i tried and what i got. Still not working.
![Screenshot from 2020-03-04 00-44-57](https://user-images.githubusercontent.com/55306738/75811392-56cc1a80-5db2-11ea-88c9-810b8dab77c1.png)

**Comment by kaiiyer** [comment]
you can't remove it by using sudo apt. Delete the binaries installed. pip remove webtech then install from the repo.

**Comment by Tawishi** [comment]
This is what worked. Working :+1:
![Screenshot from 2020-03-04 11-17-03](https://user-images.githubusercontent.com/55306738/75849060-f8cb2180-5e09-11ea-8968-1c095ab9450e.png)

**Comment by Tawishi** [comment]
Thank you for your patience and help @utkarsh-raj , @kaiiyer , @koderjoker. Also thanks to @keshakaneria for solving this issue with me.🙂
