### ISSUE TITLE
Update the burp integration to latest version

### ISSUE THREAD

**Issue by kaiiyer** [kaiiyer/webtech#24]
While integrating with burp the present version is having compatibility issues. Fix the issue with latest patches

**Comment by Pihu1998** [comment]
Hi @kaiiyer . I am interested in this issue and would like to work on it. Can you please provide some pointers for the same. It would be a great help.

**Comment by kaiiyer** [comment]
I hope you're familiar with Burp. Webtech can be integrated with burp. I've tried out the older version and it's working fine. But new version seems to have compatibility issues. So I want you to check on the issues if any with the latest version and fix it !

**Comment by Pihu1998** [comment]
Hi @kaiiyer , I would like to try on this issue if you allow. Would reach to you when I need any help.

**Comment by kaiiyer** [comment]
> Hi @kaiiyer , I would like to try on this issue if you allow. Would reach to you when I need any help.

Yeah please go ahead

**Comment by ashwinijha6** [comment]
Even I would like to try.

**Comment by kaiiyer** [comment]
Any updates @Pihu1998 ?

**Comment by aayush1205** [comment]
Might want to take this up if it is inactive.

**Comment by kaiiyer** [comment]
@utkarsh-raj Just see to it !

**Comment by Pihu1998** [comment]
Hey @kaiiyer , I tried working on this but since I am a newbie, I am finding it really hard to work on it. I guess, you should unassign me for this task and give a chance to someone else to work on this.
Really sorry for it. Thanks :)

**Comment by kaiiyer** [comment]
You should've asked for help. We have good folks who could've helped you out. Anyway check out other issues and don't hesitate to ask doubts !

**Comment by Pihu1998** [comment]
Yeah, sure @kaiiyer . Thank you :)

**Comment by ashwinijha6** [comment]
Would like to give it try

**Comment by aayush1205** [comment]
@utkarsh-raj, can I start working on this?

**Comment by koderjoker** [comment]
Reassigning this issue to @ashwinijha6 to work on

**Comment by ashwinijha6** [comment]
Ok If help needed will reach out to u koderjoker

**Comment by darkmatter18** [comment]
@kaiiyer  @koderjoker If noone is working on it, please assign me this

**Comment by kaiiyer** [comment]
@ashwinijha6 are you on it ?

> @kaiiyer @koderjoker If noone is working on it, please assign me this

**Comment by ashwinijha6** [comment]
I'm sorry for the delay .Ya I'm working on it I'll need some time.
