### ISSUE TITLE
Webtech for Windows

### ISSUE THREAD

**Issue by kaiiyer** [kaiiyer/webtech#25]
Run webtech on windows and report any bugs and issues

**Comment by ashwinijha6** [comment]
I want to work on this

**Comment by kaiiyer** [comment]
Okay I'll assign it to you !

**Comment by ashwinijha6** [comment]
![run on windows](https://user-images.githubusercontent.com/45794450/75091756-d5e17780-5596-11ea-9342-cbdce0677cc2.JPG)

**Comment by ashwinijha6** [comment]
Successfully running on windows

**Comment by arp99** [comment]
What does the option  --database-file=DATABASE_FILE do? Can you please explain?

**Comment by rajneesh44** [comment]
I want to work on this issue.

**Comment by kaiiyer** [comment]
This issue is actually resolved !!
You can look up other ones @rajneesh44
