### ISSUE TITLE
Add a logo for Webtech

### ISSUE THREAD

**Issue by kaiiyer** [kaiiyer/webtech#31]
Design a simple logo for both CLI as well as the Web version of Webtech

**Comment by harithesolo** [comment]
Can I solve this issue ?

**Comment by kaiiyer** [comment]
Yeah you're on !!

**Comment by keshakaneria** [comment]
I want to work on this issue

**Comment by kaiiyer** [comment]
@keshakaneria you can work on it too !!!

**Comment by Samriddhi25** [comment]
I also want to help in this issue.

**Comment by kaiiyer** [comment]
Yeah totally fine !!

**Comment by ashwinijha6** [comment]
I too want to work on this issue

**Comment by kaiiyer** [comment]
Go ahead !

**Comment by TheDudeThatCode** [comment]
Sir, I also want to give it a try. Please assign this to me.

**Comment by kaiiyer** [comment]
Okay cool !!

**Comment by dibyendu415** [comment]
Can I work in this issue

**Comment by kaiiyer** [comment]
Please wait for a week. Some folks are already working on this !!

**Comment by akshatj355** [comment]
I also want to design a very good and attaractive logo to this project.
