### ISSUE TITLE
It doesn't works for the websites that are banned in a country. 

### ISSUE THREAD

**Issue by akshatj355** [kaiiyer/webtech#33]
This tool doesn't works for the websites that are currently blocked in a country to scrape their data.
The Possible solution would be to try to access these websites through VPN or any other cloud solution so that we can scrape the data from other server or service provider.
Problem is open for all for a solution.
Screenshot for the problem is: 
I've tried to scrape the data of website-: https://torrentz.eu 
which is currently banned in our country.
![webtech](https://user-images.githubusercontent.com/25061121/75629124-52163380-5c05-11ea-8b9c-e23ce24bda1f.PNG)

**Comment by kaiiyer** [comment]
Oh that's a nice finding. I guess for accessing such websites we need to use a VPN. For webtech we can route the traffic through TOR which can access any website. Heard about Anonsurf ?
We can try out something like that. So do you wanna work on it ?

**Comment by akshatj355** [comment]
Yes , its a major issue to be resolved as it will help those who are interested in scaping the websites that aren't accessible in a country. 
I haven't worked on TOR or Anonsurf ever. But would like to work on same with your and other members help. Looking for Full participation.
I'm also interested in finding such kind of bugs or resolving such issues.

**Comment by akshatj355** [comment]
Hope ,i've found a good issue.

**Comment by akshatj355** [comment]
I want you to assign this issue to me only,if possible and others can help me in this.
And if I'll be unable to solve this ,then you would assign this to other member.

**Comment by akshatj355** [comment]
Hello @kaiiyer ,Anonsurf is the good option for trafficking through Tor Browser. But the important and the typical task is to integrate Anansorf with our code. Or we can try other solutions such as providing its script with the webtech package so that a user can directly install or run it. I'm working on it and also for other solutions. ,just thought to give you a short update.

**Comment by aayush1205** [comment]
@kaiiyer, let me know the status of this issue?

**Comment by kaiiyer** [comment]
@akshatj355 What's the progress be like ?

**Comment by aayush1205** [comment]
@kaiiyer, can I take this up?

**Comment by greyhatlinux** [comment]
@kaiiyer I would love to take up this issue

**Comment by kaiiyer** [comment]
@akshatj355 If you aren't responding then we'll reassign the issue !

**Comment by akshatj355** [comment]
Okk, Please reassign this issue to someone else. Sorry, for the late reply , I wasn't available for few days. 
Also, i'm unable to solve this issue.

**Comment by aayush1205** [comment]
@kaiiyer , anonsurf is for kali. It has patches for some other platforms but no luck. Moreover, I used tor to scrape banned websites but the connection still gets refuted. Moreover, setting up a VPN doesn't seem very practical. What should I do?

**Comment by kaiiyer** [comment]
No worries !
I'll fix it myself.

**Comment by greyhatlinux** [comment]
hey @kaiiyer if you don't mind 
can I give it a try ?
I won't guarantee but at least a try

**Comment by kaiiyer** [comment]
Yeah go ahead !
