### ISSUE TITLE
Links given in GitHub page aren't clickable

### ISSUE THREAD

**Issue by koderjoker** [kaiiyer/webtech#35]
**Describe the bug**
The links given under "Resources for database matching" in the repo's GitHub page aren't clickable.

![Screen Shot 2020-03-02 at 10 54 03 AM](https://user-images.githubusercontent.com/30471843/75666011-162dad80-5c9b-11ea-89a6-8cc282224196.png)

**Additional reading**
[Getting Started with GitHub Pages](https://guides.github.com/features/pages)
[Writing and formatting syntax](https://help.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax)

**Comment by aayush1205** [comment]
Please review #36
