### ISSUE TITLE
add WebTech github link with slack channel

### ISSUE THREAD

**Issue by gunjanmimo** [kaiiyer/webtech#41]
Webtech GitHub repo is not linked with slack.

Expected Behaviour
Webtech GitHub repo should be linked with slack Webtech channel for the continuous update about new pr, new issue, new commit and any merged pr.

The code will be in .yml language and add the file as slack.yml in .github/workflows/  directory.

**Comment by keshakaneria** [comment]
@gunjanmimo i would like to work on this issue

**Comment by satvikchachra** [comment]
I would like to work on it as a GSSoC participant

**Comment by gunjanmimo** [comment]
@keshakaneria great ! go ahead

**Comment by gunjanmimo** [comment]
@satvikchachra, as @keshakaneria asked first, she is assigned. if she will face any problem, then you will take this issue.

**Comment by poojasrinivass** [comment]
I would like to work on this issue

**Comment by akshatj355** [comment]
I would also like to work on it. But, mistakenly i think i've already solved the problem. It was a general issue and opened for all. Sorry Mentors for this. Please pardon me.
