### ISSUE TITLE
Add git actions workflow

### ISSUE THREAD

**Issue by kaiiyer** [kaiiyer/webtech#45]
Workflow 1: Integrating Slack with Github for notifications
Workflow 2: Add workflow for testing the code on every push operation

**Comment by keshakaneria** [comment]
Can i work on this issue and assign me, as i am solving the previous issue, which involves workflows so i am working on this too @kaiiyer

**Comment by kaiiyer** [comment]
> Can i work on this issue and assign me, as i am solving the previous issue, which involves workflows so i am working on this too @kaiiyer

Yeah go ahead !

**Comment by aayush1205** [comment]
Is this still active?

**Comment by keshakaneria** [comment]
Should i name the files as workflow 1 and 2 or edit the slack.yml file which i opened the PR #43 earlier? @kaiiyer

**Comment by kaiiyer** [comment]
leave the slack workflow as it as. Create a new file named anything.yml and submit a PR

**Comment by keshakaneria** [comment]
So basically it should have testing code right? (explain the issue briefly) because workflow 1 is comprised in slack.yml

**Comment by kaiiyer** [comment]
Workflow 1 is completed. So don't worry about it.
For workflow 2: Whenever we update the code(pushing new commits or PRs) it should check for errors. Like mypy -finding bugs in the program without even running it !

**Comment by kaiiyer** [comment]
@keshakaneria Since you're working on this. Adding a travis integration would be easier for you. So if you want you can take up issue #22 too !

**Comment by keshakaneria** [comment]
Okay, commented on that issue, if anyone isnt working on it do assign me
