### ISSUE TITLE
Possible shift from deprecated OptParse to ArgParse 

### ISSUE THREAD

**Issue by aayush1205** [kaiiyer/webtech#48]
Webtech uses OptParse which is not under active development, and for the long term good of the project, we might want to shift to argparse. If this anyhow sounds like a good idea, let me know, refactoring can be done. 

Regards.

**Comment by kaiiyer** [comment]
@aayush1205 If you want to  work on it then yeah go ahead !

**Comment by aayush1205** [comment]
@kaiiyer  You sure you should place it under easy? I might take some time to create the groups and handle arguments across the project.

**Comment by kaiiyer** [comment]
Don't worry about the time. If you make progress the issue will be all yours. After your PR let's see if this should be upgraded to medium difficulty !

**Comment by aayush1205** [comment]
@kaiiyer , All right! Will take this up as soon as possible.

**Comment by aayush1205** [comment]
@kaiiyer, I do not think handling this issue is a good idea right now. It is breaking a lot of things. What do you think I should do? Should I continue it?

**Comment by kaiiyer** [comment]
Leave it for now !
Take up some other issue and let's see if we have time for this later

**Comment by aayush1205** [comment]
Closing.

**Comment by aayush1205** [comment]
PR: #50 addresses this issue.

**Comment by aayush1205** [comment]
@kaiiyer, thanks for merging. I also wanted to request you to change the "easy" tag to whatever you deem appropriate.

**Comment by kaiiyer** [comment]
Okay !

**Comment by aayush1205** [comment]
@kaiiyer Thank you so much!

**Comment by kaiiyer** [comment]
@utkarsh-raj Update the scoresheet !
