### ISSUE TITLE
Add CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by Aman-Codes** [kaiiyer/webtech#54]
**Is your feature request related to a problem? Please describe.**
No CODE_OF_CONDUCT.md file is present.

**Describe the solution you'd like**
@kaiiyer As a GSSOC participant I would like to add a CODE_OF_CONDUCT.md file in this project.

**Additional context**

### Screenshots

![code of conduct1](https://user-images.githubusercontent.com/54680709/77505634-beddc000-6e89-11ea-9dd5-f1e13ef6c6c9.PNG)
![code of conduct2](https://user-images.githubusercontent.com/54680709/77505638-c0a78380-6e89-11ea-8aa4-efcb21133da7.PNG)

**Comment by kaiiyer** [comment]
Go ahead ! @Aman-Codes

**Comment by Aman-Codes** [comment]
@kaiiyer Would you like to share your email id in the code of conduct file where participants can report unacceptable behavior or you want to add some other channel of communication for reporting issues.

**Comment by kaiiyer** [comment]
kaiiyer47@yahoo.in

**Comment by Aman-Codes** [comment]
@kaiiyer Thank you
