### ISSUE TITLE
Add a Project Wiki page

### ISSUE THREAD

**Issue by kaiiyer** [kaiiyer/webtech#55]
Add a [wiki](https://github.com/kaiiyer/webtech/wiki) page describing the project

**Describe the solution you'd like**
Documentation regarding installation usage and project description. Use sections and pages to organize it in a user friendly manner

**Additional context**
Adding Screenshot of the tool in your local environment and the project logo would be appreciated

**Comment by greyhatlinux** [comment]
I would be happy to document this on the webtech/wiki page 😄

**Comment by kaiiyer** [comment]
Go ahead !

**Comment by ashwinijha6** [comment]
I would like to add a wiki page too

**Comment by greyhatlinux** [comment]
Hey @kaiiyer I'm done with the webtech wiki page
Have a look here : [Webtech Wiki](https://github.com/greyhatlinux/webtech/wiki)
Any correction, addition or suggestion is welcomed.  :smile: 
But, I guess there's no straight way to make a PR for a wiki page.
Please let me know the proceedings

**Comment by kaiiyer** [comment]
Just add a wiki.md file with the contents of your wiki page and sumbit a PR

> Hey @kaiiyer I'm done with the webtech wiki page
> Have a look here : [Webtech Wiki](https://github.com/greyhatlinux/webtech/wiki)
> Any correction, addition or suggestion is welcomed. smile
> But, I guess there's no straight way to make a PR for a wiki page.
> Please let me know the proceedings

**Comment by greyhatlinux** [comment]
Just made a PR with the wiki folder for the repository. #57 :smile:
