### ISSUE TITLE
It does not detect the technologies for certain urls only detects the custom headers

### ISSUE THREAD

**Issue by ashwinijha6** [kaiiyer/webtech#59]
DESCRIPTION OF THE BUG

The command webtech -u or webtech --urls with the url(s) to scan, which scans the url & identifies the technologies used on the website & detects interesting custom headers does not detect the technologies for certain urls & only detects the custom headers as mentioned below.

TO REPRODUCE

Steps to reproduce the behaviour:
(1) Go to terminal
(2) Pip install Webtech by using the command 'pip install webtech'
(3) Then use the command webtech -u or webtech --urls with the url(s) to scan.
(4) Try for url(s) such as:-
    webtech -u https://www.faceook.com/
    webtech -u https://www.twitter.com/
    webtech -u https://www.instagram.com/
(5) See the error.

EXPECTED BEHAVIOUR

It must detect the technologies & the custom headers for every url used with the command webtech -u or webtech --urls.

SCREENSHOTS

Are attached below.

DESKTOP

OS:     Linux
Distro: ubuntu 16.04 LTS

The screenshot is attached.
![bug1](https://user-images.githubusercontent.com/45794450/78670034-c88c0c80-78fa-11ea-917f-a60cf347b388.jpg)

**Comment by kaiiyer** [comment]
Okay so wanna work on this issue @ashwinijha6 ?

**Comment by ashwinijha6** [comment]
Ya I want to try solving it.
Can u assign it to me?

**Comment by kaiiyer** [comment]
> Ya I want to try solving it.
> Can u assign it to me?

All set now !

**Comment by ashwinijha6** [comment]
Yeah

**Comment by ashwinijha6** [comment]
Final files for issue #59 is the correct pull request
